version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/postgres:12-alpine
        name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: awesome_test
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ./gradlew test
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

workflows:
  version: 2
  workflow:
    jobs:
    - build

    